<?php

namespace lOro\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntregasMinoristasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntregasMinoristasRepository extends EntityRepository
{


  
  public function findEntregasMinoristas() { 
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT em.id,
                 em.fe_entrega AS feEntrega,
                 em.minorista_id AS minoristaId,
                 m.nb_proveedor AS nbMinorista,
                 em.peso_bruto_entrega AS pesoBrutoEntrega,
                 em.ley AS leyAproximada,
                 em.peso_puro_entrega AS pesoPuroEntrega,
                 em.ubicacion_fisica_entrega AS ubicacionFisicaEntrega
          FROM entregas_minoristas AS em
          JOIN proveedores AS m ON (m.id = em.minorista_id)
          ORDER BY fe_entrega DESC;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetchAll();    
  }
  
  public function balanceTotalMinoristas() { 
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT SUM(vcmm.credito_mensual_minorista) AS credito
          FROM v_creditos_mensuales_por_minorista AS vcmm;";
        
    $stmt = $conn->executeQuery($q);
    
    $sumCredito = $stmt->fetch();
    
    
    $q = "SELECT SUM(vpmm.debito_mensual_minorista) AS debito
          FROM v_pagos_mensuales_por_minorista AS vpmm;";
        
    $stmt = $conn->executeQuery($q);
    
    $sumDebito = $stmt->fetch();    
    
    $q = "SELECT SUM(e.total_monto_bs) AS total_restante FROM entregas_minoristas AS e WHERE e.fe_entrega < '2015-10-26' LIMIT 1; ";
    
    $stmt = $conn->executeQuery($q);
    
    $restanteAntesPagosMinoristas = $stmt->fetch(); // Esto es lo que antes se manejaba por pagos varios
    
    $balanceTotal = ($sumCredito['credito'] > 0 ? $sumCredito['credito'] : 0) - (($sumDebito['debito'] > 0 ? $sumDebito['debito'] : 0) + $restanteAntesPagosMinoristas['total_restante']);
    
    return $balanceTotal;
  } 
  
  public function pagosMinoristas() { 
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT SUM(em.debito_mensual_minorista) AS total_pagos_minoristas
          FROM v_pagos_mensuales_por_minorista AS em;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetch();    
  }  

  public function creditosMinoristas() { 
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT SUM(em.credito_mensual_minorista) AS total_credito_minoristas
          FROM v_creditos_mensuales_por_minorista AS em;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetchAll();    
  }    
}
