<?php

namespace lOro\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BalancesGananciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalancesGananciaRepository extends EntityRepository
{
    public function getSumOfRefAvgPayments() {
      $conn = $this->getEntityManager()->getConnection();
           
      $stmt = $conn->executeQuery("SELECT SUM(debito) AS total FROM ref_avg_sum_payments;");
            
      $result = $stmt->fetch();
         
      return $result['total'];
    }

    public function getVCierresProveedorPorMesAnioAction($mes,$anio) {
      $conn = $this->getEntityManager()->getConnection();
           
      $stmt = $conn->executeQuery("SELECT *
                                   FROM v_cierres_por_mes_anio_proveedores AS cmap
                                   WHERE cmap.mes = '$mes'
                                   AND cmap.anio = '$anio';");
            
           
      return $stmt->fetchAll();
    }
        
    public function getVCierresEntregasParaComparacionTiempo($feDesde,$feHasta,$idProveedor = null) {
      $conn = $this->getEntityManager()->getConnection();
           
      $sqlProveedor = ($idProveedor ? "AND e.proveedor_id = $idProveedor" : "");
      
      $sql = "SELECT vc.id AS id_cierre,
                     p.nb_proveedor,
                     pz.id AS id_pieza, 
                     vc.monto_bs_cierre_por_gramo,
                     vc.valor_onza,
                     vc.estatus,
                     e.id AS id_entrega,
                     cpp.material_entregado, 
                     pz.cod_pieza, 
                     pz.peso_bruto_pieza, 
                     pz.peso_puro_pieza, 
                     pz.ley_pieza, 
                     vc.fe_venta, 
                     vc.cantidad_total_venta, 
                     e.fe_entrega,
                     vc.dolar_referencia_dia,
                     ((((((vc.valor_onza/31.1035)*0.97)*vc.dolar_referencia_dia) - vc.monto_bs_cierre_por_gramo)*cpp.material_entregado)/vc.dolar_referencia_dia) AS ganancia_pieza
              FROM cierres_proveedores_piezas AS cpp 
              JOIN ventas_cierres AS vc ON (vc.id = cpp.cierre_proveedor_id) 
              JOIN piezas AS pz ON (pz.id = cpp.pieza_id) JOIN entregas AS e ON (e.id = pz.entrega_id) 
              JOIN proveedores AS p ON (p.id = vc.proveedor_id)
              WHERE vc.fe_venta BETWEEN '$feDesde' AND '$feHasta'
              $sqlProveedor
              ORDER BY vc.fe_venta DESC;";
     
     
     $stmt = $conn->executeQuery($sql);

      return $stmt->fetchAll();
    } 
    
}
