<?php

namespace lOro\EntityBundle\Entity\Repository;

/**
 * BaseMontosExtraordinariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseMontosExtraordinariosRepository extends \Doctrine\ORM\EntityRepository
{
  public function sumarMontos() {
      $rep = $this->getEntityManager()->getRepository('lOroEntityBundle:BaseMontosExtraordinarios');
      
      $q = $rep->createQueryBuilder('bme')
                ->select("sum(bme.monto) as totalMontosExtraordinarios")
                ->getQuery();
      
      return $q->setMaxResults(1)->getOneOrNullResult();
  }    
}
