<?php

namespace lOro\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MinoristasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinoristasRepository extends EntityRepository
{
    
    
  public function findPagosMinorista($idMinorista) {
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT SUM(pm.monto_pagado) AS total_pagado
          FROM pagos_minoristas AS pm
          JOIN empresas_proveedores AS ep ON (ep.id = pm.empresa_proveedor_id) 
          WHERE pm.fe_pago >= '2015-10-26' AND ep.proveedor_id = $idMinorista;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetch();       
  }
  
  public function findCierresPorMinorista($idMinorista) {
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT p.id,
                 p.nb_proveedor,
                 SUM(e.total_monto_bs) AS total_monto_cierres
          FROM entregas_minoristas AS e 
          JOIN proveedores AS p ON (p.id = e.minorista_id)
          WHERE e.fe_entrega >= '2015-10-26'
          AND p.id = $idMinorista;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetch();       
  }
  
  public function findBalanceAdeudadoMatMinoristas($idMinorista) {
    $conn = $this->getEntityManager()->getConnection();
      
    $q = "SELECT *
          FROM v_balance_mat_minoristas  AS bmm
          WHERE id = $idMinorista;";
        
    $stmt = $conn->executeQuery($q);
                    
    return $stmt->fetch();           
  }
  
  public function findCreditosTotalesPorMinoristas() {
     $conn = $this->getEntityManager()->getConnection();
           
      $sql = "SELECT cmpm.id_minorista,
                     SUM(cmpm.credito_mensual_minorista) AS cred_total_minorista
              FROM v_creditos_mensuales_por_minorista AS cmpm
              GROUP BY cmpm.id_minorista;";
     
     
     $stmt = $conn->executeQuery($sql);

      return $stmt->fetchAll();      
  }
  
  public function findPagosTotalesPorMinoristas() {
     $conn = $this->getEntityManager()->getConnection();
           
      $sql = "SELECT cmpm.id_proveedor,
                     SUM(cmpm.debito_mensual_minorista) AS pag_total_minorista
              FROM v_pagos_mensuales_por_minorista AS cmpm
              GROUP BY cmpm.id_proveedor;";
     
     
     $stmt = $conn->executeQuery($sql);

      return $stmt->fetchAll();      
  }  
}
