<?php

namespace lOro\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagosVariosRepository extends EntityRepository
{
    public function buscarPorId($valorBusqueda)
    {      
      $valorBusqueda = ($valorBusqueda ? $valorBusqueda : '');
      
      $qb = $this->createQueryBuilder('u');
      $result = $qb ->select('u')
                    ->where(
                      $qb->expr()->like('u.id',$qb->expr()->literal('%'. $valorBusqueda . '%'))
                    )
                    ->orderBy('u.id','DESC')
       ->getQuery()   
       ->getResult();
       
      return $result;
    }
    
    public function buscarPorFechas($feInicio,$feFinal) 
    {
      return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                 FROM lOroEntityBundle:PagosVarios e
                 WHERE (e.fePago
                 BETWEEN :feInicio AND :feFinal)
                 ORDER BY e.id DESC'
            )
            ->setParameter('feInicio', new \ DateTime($feInicio))
            ->setParameter('feFinal', new \ DateTime($feFinal))
            ->getResult();
      }
      
      public function buscarPorEmpresaCasa($idEmpresaCasa) {
          
      return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                 FROM lOroEntityBundle:PagosVarios e
                 JOIN e.empresaCasa AS ec
                 WHERE ec.id = :idEmpresaCasa
                 ORDER BY e.id DESC'
            )
            ->setParameter('idEmpresaCasa', $idEmpresaCasa)
            ->getResult();          
      }
      
      public function findPagosVariosPorMeseAnio($anio,$mes) {
        $conn = $this->getEntityManager()->getConnection();
      
        $config = $this->getEntityManager()->getConfiguration();
        $config->addCustomNumericFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        $config->addCustomNumericFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');

        $sqlAnio = ($anio == 999 ? '' : "AND YEAR(pv.fe_pago) = $anio");
        $sqlMes = ($mes == 999 ? '' : " AND MONTH(pv.fe_pago) = $mes");
        
        
        $queryMensual = "SELECT SUM(pv.monto_pago) AS total_pagado,
                                MONTH(pv.fe_pago) AS mes,
                                YEAR(pv.fe_pago) AS anio,
                                tpv.id,
                                tpv.descripcion
                         FROM pagos_varios AS pv
                         JOIN tipo_pagos_varios AS tpv ON (pv.tipo_pago_vario_id = tpv.id) 
                         $sqlAnio
                         $sqlMes
                         GROUP BY MONTH(pv.fe_pago), YEAR(pv.fe_pago),tpv.descripcion, tpv.id;";
        
        
        $stmt = $conn->executeQuery($queryMensual);
            
            
      return $stmt->fetchAll();
      }
}
