<?php

namespace lOro\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * TransferenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciasRepository extends EntityRepository
{
    public function sumatoriaDolaresTransferidosHc($balanceActivo) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sum(t.montoTransferencia) AS totalTransferencias
                 FROM lOroEntityBundle:Transferencias AS t
                 WHERE t.balance = :balanceActivo'
            )
            ->setParameter(':balanceActivo',$balanceActivo)
            ->getSingleResult();
    }
}