<?php

namespace lOro\EntityBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * TransferenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentasEntregasRepository extends EntityRepository
{
    public function findAllVentasEntregasMayoresA($ventasCierre) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM lOroEntityBundle:VentasEntregas e WHERE e.ventasCierres >= :ventasCierre'
            )
            ->setParameter('ventasCierre',$ventasCierre)
            ->getResult();        
    }
}
